# Generated by Django 4.2.1 on 2023-07-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_interview',
            name='interview_Slot_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to='applicants.interview_slot'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_ID',
            field=models.CharField(db_index=True, max_length=13, verbose_name='National ID Card Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, verbose_name='Phone Number'),
        ),
    ]
