# Generated by Django 4.2.1 on 2023-07-12 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_candidate_interview_interview_slot_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview_slot',
            name='slot_group_ID',
        ),
        migrations.AlterField(
            model_name='candidate_interview',
            name='interview_Slot_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to='applicants.interview_slot'),
        ),
        migrations.AddField(
            model_name='interview_slot',
            name='slot_Group_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='applicants.slot_group', verbose_name='Group of the slot'),
            preserve_default=False,
        ),
    ]
