# Generated by Django 4.2.1 on 2023-07-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_candidate_interview_candidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_interview',
            name='interview_Slot_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_interviews', to='applicants.interview_slot'),
        ),
    ]
