# Generated by Django 4.2.1 on 2023-07-17 07:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_alter_candidate_interview_interview_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Job Description'),
        ),
    ]
