# Generated by Django 4.2.1 on 2023-07-17 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_job_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='overview',
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=ckeditor.fields.RichTextField(default='This is an initial Qualifications entry.', verbose_name='Job Qualifications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(default='This is an initial responsibilities entry', verbose_name='Job Responsibilities'),
            preserve_default=False,
        ),
    ]
