# Generated by Django 4.2.1 on 2023-07-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_rename_description_job_overview_job_qualifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_application',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='candidate_Application_ID',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='applicants.candidate_application'),
            preserve_default=False,
        ),
    ]
