# Generated by Django 4.2.1 on 2023-07-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_remove_candidate_application_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_application',
            name='reference',
        ),
        migrations.AddField(
            model_name='reference',
            name='candidate_Application_ID',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='applicants.candidate_application'),
            preserve_default=False,
        ),
    ]
